# Find more information on toml format here:  https://github.com/toml-lang/toml
# ModLoader settings
modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
updateJSONURL="https://immortius.xyz/museumcurator/updates.json"
displayURL="https://immortius.xyz/museumcurator"
logoFile="museumcuratorlogo.png"
authors="${mod_author}"
description='''${description}'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_loader_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
